name: Build, Test, and Push to Docker Hub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_REPO || format('{0}/{1}', secrets.DOCKERHUB_USERNAME, github.repository) }}:latest

      - name: Run tests
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_REPO || format('{0}/{1}', secrets.DOCKERHUB_USERNAME, github.repository) }}:latest npm test

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO || format('{0}/{1}', secrets.DOCKERHUB_USERNAME, github.repository) }}:latest
